# Generated by Django 5.2.7 on 2025-11-09 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=15)),
                ('photo', models.FileField(upload_to='photos')),
                ('id_proof', models.FileField(upload_to='photos')),
                ('approval_status', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blind_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=15)),
                ('photo', models.FileField(upload_to='photos')),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('radius', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('reply', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.CharField(max_length=15)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.FileField(upload_to='photos')),
                ('BLIND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.CharField(max_length=15)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caretaker')),
            ],
        ),
    ]
