# Generated by Django 5.2.7 on 2025-11-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blind_user',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
