# Generated by Django 5.2.7 on 2025-11-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blind_user_email_alter_caretaker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='gender',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='photo',
            field=models.FileField(upload_to='caretaker_photos/'),
        ),
    ]
